import {
  Award,
  BarChart3,
  Beer,
  BookOpen,
  Camera,
  Check,
  ChevronsUp,
  Circle,
  CircleDashed,
  CircleDot,
  Clapperboard,
  Clock,
  Coins,
  Copy,
  Crown,
  Dices,
  Download,
  Dumbbell,
  Eye,
  EyeOff,
  Film,
  Flag,
  Flame,
  Gem,
  Hand,
  Handshake,
  Hash,
  Heart,
  HelpCircle,
  Hourglass,
  Image as ImageIcon,
  Link2,
  Lock,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquareReply,
  Mic,
  Moon,
  PartyPopper,
  Pause,
  Pencil,
  Phone,
  Play,
  Reply,
  RotateCw,
  Send,
  Shield,
  ShowerHead,
  Skull,
  Smartphone,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Swords,
  Target,
  ThumbsUp,
  Ticket,
  Trash2,
  TriangleAlert,
  Trophy,
  User,
  Users,
  Video,
  Wind,
  WifiOff,
  Wine,
  X,
  Zap,
} from "lucide-react-native";

import { INK } from "@/lib/ui";

/**
 * Appens symbolvokabulär. Allt UI-chrome använder linjeikoner härifrån i
 * stället för emojis — emojis lever bara kvar i meddelanden och reaktioner.
 *
 * Data-moduler (t.ex. huntCards.ts, chatSettings.ts) är rena .ts-filer och
 * kan inte hålla komponenter. De lagrar i stället ett namn härifrån, och
 * vyn renderar det med <AppIcon />.
 */
export const APP_ICONS = {
  award: Award,
  bar: Beer,
  beer: Beer,
  book: BookOpen,
  camera: Camera,
  chart: BarChart3,
  check: Check,
  clock: Clock,
  coins: Coins,
  copy: Copy,
  crown: Crown,
  dice: Dices,
  dot: CircleDot,
  download: Download,
  edit: Pencil,
  export: Download,
  eye: Eye,
  eyeOff: EyeOff,
  film: Film,
  flag: Flag,
  fire: Flame,
  freeze: Snowflake,
  gem: Gem,
  hand: Hand,
  handshake: Handshake,
  hash: Hash,
  heart: Heart,
  help: HelpCircle,
  hole: CircleDashed,
  hourglass: Hourglass,
  image: ImageIcon,
  level: ChevronsUp,
  link: Link2,
  lock: Lock,
  medal: Medal,
  message: MessageCircle,
  mic: Mic,
  offline: WifiOff,
  party: PartyPopper,
  pause: Pause,
  phone: Phone,
  play: Play,
  poll: BarChart3,
  reply: Reply,
  ring: Circle,
  send: Send,
  shield: Shield,
  shower: ShowerHead,
  skull: Skull,
  sprout: Sprout,
  smartphone: Smartphone,
  sleep: Moon,
  sparkles: Sparkles,
  spin: RotateCw,
  star: Star,
  strength: Dumbbell,
  swords: Swords,
  target: Target,
  thread: MessageSquareReply,
  thumb: ThumbsUp,
  ticket: Ticket,
  trash: Trash2,
  trophy: Trophy,
  user: User,
  users: Users,
  video: Video,
  voice: Megaphone,
  warning: TriangleAlert,
  wind: Wind,
  wine: Wine,
  x: X,
  zap: Zap,
} as const;

export type AppIconName = keyof typeof APP_ICONS;

/**
 * Linjeikon i appens stil. `strokeWidth` 1.8 matchar Feather-ikonerna i
 * <Icon />, så de två uppsättningarna kan stå bredvid varandra.
 */
export function AppIcon({
  name,
  size = 18,
  color = INK,
  strokeWidth = 1.8,
}: {
  name: AppIconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
}) {
  const Cmp = APP_ICONS[name];
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} />;
}
