/** 1000+ frågor till "Vem är mest trolig" (1096 st, alla unika). Uppdelade i
 * kategorier för läsbarhet — exporteras som en enda platt lista. Håll varje rad unik. */

const FEST_OCH_FYLLA = [
  "Vem är mest trolig att somna först ikväll?",
  "Vem är mest trolig att gråta på en fest?",
  "Vem är mest trolig att tappa bort sin telefon ikväll?",
  "Vem är mest trolig att bli hemskickad från förfesten?",
  "Vem är mest trolig att beställa en runda till fast alla vill gå hem?",
  "Vem är mest trolig att börja hålla tal utan anledning?",
  "Vem är mest trolig att dansa på ett bord innan midnatt?",
  "Vem är mest trolig att bli bästa vän med utkastaren?",
  "Vem är mest trolig att förlora sin jacka på krogen?",
  "Vem är mest trolig att ta med sig fel jacka hem?",
  "Vem är mest trolig att somna med skorna på?",
  "Vem är mest trolig att beställa käk till hela gänget klockan tre?",
  "Vem är mest trolig att starta allsång på bussen hem?",
  "Vem är mest trolig att kräkas i en rabatt?",
  "Vem är mest trolig att tappa bort hela sällskapet direkt?",
  "Vem är mest trolig att bjuda okända på shots?",
  "Vem är mest trolig att bli portad från ett ställe ikväll?",
  "Vem är mest trolig att försöka klättra över ett staket helt i onödan?",
  "Vem är mest trolig att vakna på en soffa hos någon okänd?",
  "Vem är mest trolig att ringa sin mamma från dansgolvet?",
  "Vem är mest trolig att förlora ett vad under kvällen?",
  "Vem är mest trolig att börja gråta till en viss låt?",
  "Vem är mest trolig att glömma var festen är?",
  "Vem är mest trolig att ta mikrofonen från DJ:n?",
  "Vem är mest trolig att spilla drink på någon annan inom en timme?",
  "Vem är mest trolig att gå hem utan att säga hejdå?",
  "Vem är mest trolig att stanna kvar och städa efter festen?",
  "Vem är mest trolig att vara sist kvar på dansgolvet?",
  "Vem är mest trolig att beställa vatten och låtsas att det är vodka?",
  "Vem är mest trolig att utse sig själv till kvällens fotograf?",
  "Vem är mest trolig att tappa sin öl och beställa två nya?",
  "Vem är mest trolig att hamna i en djup diskussion med en taxichaufför?",
  "Vem är mest trolig att bli kvar i baren när alla andra dragit vidare?",
  "Vem är mest trolig att försöka övertala alla att åka till en till klubb?",
  "Vem är mest trolig att somna på toaletten på en klubb?",
  "Vem är mest trolig att glömma sin legitimation hemma?",
  "Vem är mest trolig att köpa rundor tills kortet spärras?",
  "Vem är mest trolig att vinna en dansbattle på klubben?",
  "Vem är mest trolig att förolämpa DJ:ns låtval högt?",
  "Vem är mest trolig att önska samma låt tre gånger?",
  "Vem är mest trolig att bli fotad i pinsam pose och hamna på nätet?",
  "Vem är mest trolig att förlora sina nycklar på vägen hem?",
  "Vem är mest trolig att gå in i en glasdörr på krogen?",
  "Vem är mest trolig att bli kär i någon efter fem minuters snack?",
  "Vem är mest trolig att avsluta kvällen med en kebabrulle i vardera hand?",
  "Vem är mest trolig att lova saker på fyllan som aldrig blir av?",
  "Vem är mest trolig att bli vän med kökspersonalen på afterparty?",
  "Vem är mest trolig att ta av sig skorna mitt på dansgolvet?",
  "Vem är mest trolig att starta karaoke fast det inte är karaokekväll?",
  "Vem är mest trolig att gå fel på vägen hem trots GPS?",
  "Vem är mest trolig att vakna med en okänd hatt?",
  "Vem är mest trolig att övertyga gruppen om 'en sista öl' fem gånger?",
  "Vem är mest trolig att glömma att de har förfest hemma hos sig?",
  "Vem är mest trolig att bjuda hela baren på en runda av misstag?",
  "Vem är mest trolig att hålla ett tårfyllt tal om vänskap klockan 02?",
  "Vem är mest trolig att försöka betala med fel kort hela kvällen?",
  "Vem är mest trolig att tappa rösten efter en kväll ute?",
  "Vem är mest trolig att beställa den konstigaste drinken på menyn?",
  "Vem är mest trolig att smyga hem tidigt utan att någon märker?",
  "Vem är mest trolig att vara den som alltid vill ta gruppbild?",
  "Vem är mest trolig att hamna bakom baren och börja hjälpa till?",
  "Vem är mest trolig att utmana en främling i armbrytning?",
  "Vem är mest trolig att somna i taxin och åka en extra runda?",
  "Vem är mest trolig att kalla alla för 'brorsan' efter midnatt?",
  "Vem är mest trolig att förlora sin ena sko utan att märka det?",
  "Vem är mest trolig att skriva upp sig på öppen mic spontant?",
  "Vem är mest trolig att beställa dagens sista mat på snabbmatstället?",
  "Vem är mest trolig att gå runt och krama alla på festen?",
  "Vem är mest trolig att hitta på en egen drink och döpa den efter sig själv?",
  "Vem är mest trolig att svära på att de är nyktra fast de inte är det?",
  "Vem är mest trolig att bli kvällens självutnämnda livvakt?",
  "Vem är mest trolig att tappa bort sig på en festival?",
  "Vem är mest trolig att campa längst fram vid scenen hela dagen?",
  "Vem är mest trolig att köpa merch för hela månadslönen på konsert?",
  "Vem är mest trolig att starta en konga-kö?",
  "Vem är mest trolig att sjunga fel text högst av alla?",
  "Vem är mest trolig att bli upplyft på scen av artisten?",
  "Vem är mest trolig att fastna i vaktkontrollen med konstiga fickfynd?",
  "Vem är mest trolig att dricka upp någon annans drink av misstag?",
  "Vem är mest trolig att hålla i spelledningen på varje förfest?",
  "Vem är mest trolig att ta ansvar när någon mår dåligt på festen?",
  "Vem är mest trolig att glömma hela kvällen och kräva en sammanfattning?",
  "Vem är mest trolig att skicka 'var är ni?' tjugo gånger på en kväll?",
  "Vem är mest trolig att lova att inte dricka och ändå vara värst?",
  "Vem är mest trolig att bli fast i garderobskön hela natten?",
  "Vem är mest trolig att förhandla med krögaren om notan?",
  "Vem är mest trolig att adoptera en hel kompisgrupp på en kväll?",
  "Vem är mest trolig att bli nekad i dörren för sina skor?",
  "Vem är mest trolig att ha en powernap mitt under festen och komma tillbaka starkare?",
  "Vem är mest trolig att beställa bordsbokning med flaskservice helt omotiverat?",
  "Vem är mest trolig att vara den som alla frågar 'vad hände igår?'",
  "Vem är mest trolig att vinna beerpong-turneringen?",
  "Vem är mest trolig att förlora i beerpong mot en nybörjare?",
  "Vem är mest trolig att gömma en öl på ett hemligt ställe till senare?",
  "Vem är mest trolig att ta studentflaket-energin till en vanlig lördag?",
  "Vem är mest trolig att komma till efterfesten före värden?",
  "Vem är mest trolig att somna stående?",
  "Vem är mest trolig att beställa espresso martini när alla andra tar öl?",
  "Vem är mest trolig att hålla låda i jacuzzin tills solen går upp?",
];

const KARLEK_OCH_DEJTING = [
  "Vem är mest trolig att gifta sig först?",
  "Vem är mest trolig att svara sitt ex klockan 03?",
  "Vem är mest trolig att bli kär på första dejten?",
  "Vem är mest trolig att glömma sin partners födelsedag?",
  "Vem är mest trolig att fria på en storbildsskärm?",
  "Vem är mest trolig att ha flest matchningar på dejtingappar?",
  "Vem är mest trolig att gå på två dejter samma dag?",
  "Vem är mest trolig att bli tillsammans med en kändis?",
  "Vem är mest trolig att skriva ett kärleksbrev för hand?",
  "Vem är mest trolig att bli ihop med sin barndomskärlek?",
  "Vem är mest trolig att ghosta någon efter tre dejter?",
  "Vem är mest trolig att bli ghostad och inte fatta det på en månad?",
  "Vem är mest trolig att dejta någon dubbelt så gammal?",
  "Vem är mest trolig att presentera en ny partner på varje släktmiddag?",
  "Vem är mest trolig att gifta sig i Las Vegas?",
  "Vem är mest trolig att ha ett hemligt förhållande just nu?",
  "Vem är mest trolig att stalka en dejt på nätet innan första träffen?",
  "Vem är mest trolig att säga 'jag älskar dig' först?",
  "Vem är mest trolig att skaffa matchande tatuering med en partner?",
  "Vem är mest trolig att bli lämnad för att de snarkar?",
  "Vem är mest trolig att ta med en dejt på extremsport?",
  "Vem är mest trolig att laga en trerätters middag på första dejten?",
  "Vem är mest trolig att glömma var de parkerat mitt under en dejt?",
  "Vem är mest trolig att bli ihop med grannen?",
  "Vem är mest trolig att flytta ihop efter en månad?",
  "Vem är mest trolig att ha en lista med krav på framtida partner?",
  "Vem är mest trolig att dejta två personer med samma namn i rad?",
  "Vem är mest trolig att bli fångad på kysskameran på en match?",
  "Vem är mest trolig att gråta på någon annans bröllop?",
  "Vem är mest trolig att fånga brudbuketten?",
  "Vem är mest trolig att hålla det pinsammaste bröllopstalet?",
  "Vem är mest trolig att bli föremål för en romantisk gest offentligt?",
  "Vem är mest trolig att säga fel namn i ett känsligt läge?",
  "Vem är mest trolig att ha kvar bilder på sitt ex?",
  "Vem är mest trolig att bli vän med alla sina ex?",
  "Vem är mest trolig att aldrig våga ta första steget?",
  "Vem är mest trolig att flörta med servitören helt omedvetet?",
  "Vem är mest trolig att skicka fel meddelande till fel person?",
  "Vem är mest trolig att planera hela bröllopet innan andra dejten?",
  "Vem är mest trolig att gifta sig utomlands utan att säga något?",
  "Vem är mest trolig att ha en dejt som slutar med akuten?",
  "Vem är mest trolig att bli kär i någon på semestern?",
  "Vem är mest trolig att hålla kontakten med en semesterromans i tio år?",
  "Vem är mest trolig att skriva dikter till sin partner?",
  "Vem är mest trolig att glömma årsdagen två år i rad?",
  "Vem är mest trolig att ordna den mest genomtänkta överraskningen?",
  "Vem är mest trolig att bli ihop med någon från gymmet?",
  "Vem är mest trolig att dejta någon för deras hund?",
  "Vem är mest trolig att avsluta ett förhållande via sms?",
  "Vem är mest trolig att bli lämnad via lapp på kylskåpet?",
  "Vem är mest trolig att ragga med samma replik i tio år?",
  "Vem är mest trolig att gå på blindträff ordnad av sin mormor?",
  "Vem är mest trolig att hitta kärleken i mataffären?",
  "Vem är mest trolig att ha högst standard och lägst tålamod?",
  "Vem är mest trolig att bli förälskad i en röst innan de sett personen?",
  "Vem är mest trolig att dejta någon som deras kompisar avskyr?",
  "Vem är mest trolig att fråga chans som vuxen?",
  "Vem är mest trolig att ordna picknick-dejt i regn?",
  "Vem är mest trolig att bli nervös och prata non-stop på dejt?",
  "Vem är mest trolig att glömma att de redan har en dejt inbokad?",
  "Vem är mest trolig att bli kär i sin bästa väns syskon?",
  "Vem är mest trolig att säga upp sig och flytta för kärleken?",
  "Vem är mest trolig att ha ett bröllop med tema?",
  "Vem är mest trolig att vilja ha 200 gäster på bröllopet?",
  "Vem är mest trolig att rymma från sitt eget bröllop?",
  "Vem är mest trolig att bli tillsammans med någon de träffade i en kö?",
  "Vem är mest trolig att ha flest 'nästan-förhållanden'?",
  "Vem är mest trolig att analysera varje sms i gruppchatten?",
  "Vem är mest trolig att be kompisarna godkänna en dejt i förväg?",
  "Vem är mest trolig att ta med en dejt på släktkalas för tidigt?",
  "Vem är mest trolig att bli kär i en kollega?",
  "Vem är mest trolig att hemlighålla ett förhållande i ett år?",
  "Vem är mest trolig att skriva ett raggningsmeddelande med stavfel i första ordet?",
  "Vem är mest trolig att bjuda på dejt och glömma plånboken?",
  "Vem är mest trolig att välja restaurang efter var det är billigast?",
  "Vem är mest trolig att ta en dejt till samma ställe varje gång?",
  "Vem är mest trolig att bli ihop med någon via ett spel online?",
  "Vem är mest trolig att skicka röstmeddelanden på fem minuter till sin crush?",
  "Vem är mest trolig att ha en playlist för varje förhållande?",
  "Vem är mest trolig att gråta till romantiska komedier?",
  "Vem är mest trolig att säga 'vi ses' och sedan aldrig höra av sig?",
  "Vem är mest trolig att svartsjukt kolla vem som gillat partnerns bilder?",
  "Vem är mest trolig att fria först i kompisgänget?",
  "Vem är mest trolig att skaffa barn först?",
  "Vem är mest trolig att döpa sitt barn efter en fotbollsspelare?",
  "Vem är mest trolig att bli den överdrivet kära föräldern på plan?",
  "Vem är mest trolig att ha flest bilder på sin partner i plånboken?",
  "Vem är mest trolig att glömma alla hjärtans dag?",
  "Vem är mest trolig att överdriva alla hjärtans dag totalt?",
  "Vem är mest trolig att bli ihop, göra slut och bli ihop igen samma vecka?",
  "Vem är mest trolig att låta kompisarna välja deras nästa dejt?",
  "Vem är mest trolig att bli kär i någon på bussen och aldrig säga något?",
  "Vem är mest trolig att dejta någon enbart för deras matlagning?",
  "Vem är mest trolig att flytta till en annan kontinent för en crush?",
  "Vem är mest trolig att ha världens längsta förlovning?",
  "Vem är mest trolig att gifta sig på en vardag för att det var billigare?",
  "Vem är mest trolig att hålla handen på bio redan första dejten?",
  "Vem är mest trolig att skriva kontaktannons på gammaldags vis?",
  "Vem är mest trolig att bli mest tårögd av alla på sin egen vigsel?",
  "Vem är mest trolig att ha ett ex i varje stad?",
];

const PENGAR_OCH_KARRIAR = [
  "Vem är mest trolig att bli miljonär?",
  "Vem är mest trolig att starta ett företag som går i konkurs?",
  "Vem är mest trolig att bli chef över oss andra?",
  "Vem är mest trolig att vinna på lotto och slösa bort allt på ett år?",
  "Vem är mest trolig att glömma att betala en räkning tre månader i rad?",
  "Vem är mest trolig att bli rik på en helt galen affärsidé?",
  "Vem är mest trolig att jobba kvar på samma ställe hela livet?",
  "Vem är mest trolig att byta karriär helt efter 40?",
  "Vem är mest trolig att säga upp sig i ren frustration?",
  "Vem är mest trolig att bli befordrad utan att ens söka?",
  "Vem är mest trolig att somna på ett viktigt möte?",
  "Vem är mest trolig att skicka ett klagomejl till fel chef?",
  "Vem är mest trolig att bli fast i hisspitch med VD:n?",
  "Vem är mest trolig att förhandla upp sin lön mest?",
  "Vem är mest trolig att jobba gratis för att de inte vågar fråga om lön?",
  "Vem är mest trolig att starta eget innan 30?",
  "Vem är mest trolig att investera i något ingen förstår?",
  "Vem är mest trolig att köpa aktier på toppen och sälja på botten?",
  "Vem är mest trolig att ha ett Excel-ark för allt?",
  "Vem är mest trolig att låna ut pengar och aldrig våga be om dem tillbaka?",
  "Vem är mest trolig att bli ekonomiskt oberoende först?",
  "Vem är mest trolig att köpa en båt de inte har råd med?",
  "Vem är mest trolig att pruta på loppis tills säljaren ger upp?",
  "Vem är mest trolig att betala fullpris utan att ens kolla priset?",
  "Vem är mest trolig att glömma var de lagt sina sparpengar?",
  "Vem är mest trolig att bli rik och ändå snåla på kaffet?",
  "Vem är mest trolig att bjuda hela gänget när lönen kommit?",
  "Vem är mest trolig att ha tre sidoprojekt samtidigt?",
  "Vem är mest trolig att bli konsult och tredubbla lönen?",
  "Vem är mest trolig att ta ett sabbatsår som blir fem?",
  "Vem är mest trolig att pensionera sig vid 45?",
  "Vem är mest trolig att jobba till 75 för att de gillar det?",
  "Vem är mest trolig att bli årets medarbetare?",
  "Vem är mest trolig att bli utbränd av att säga ja till allt?",
  "Vem är mest trolig att svara på jobbmejl på semestern?",
  "Vem är mest trolig att vägra kolla jobbmejl efter 17?",
  "Vem är mest trolig att starta ett fikaimperium?",
  "Vem är mest trolig att sälja sin startup för en miljard?",
  "Vem är mest trolig att köpa hus först?",
  "Vem är mest trolig att bo i husvagn av fri vilja?",
  "Vem är mest trolig att renovera ett hus helt själv?",
  "Vem är mest trolig att anlita hantverkare för att byta en glödlampa?",
  "Vem är mest trolig att glömma sitt kortpin mitt i kassakön?",
  "Vem är mest trolig att swisha fel person och skämmas för mycket för att be om pengarna?",
  "Vem är mest trolig att ha koll på exakt vad alla är skyldiga?",
  "Vem är mest trolig att alltid 'glömma' plånboken?",
  "Vem är mest trolig att köpa lunch ute varje dag i tio år?",
  "Vem är mest trolig att ha matlåda med sig överallt?",
  "Vem är mest trolig att bli handplockad till ett drömjobb?",
  "Vem är mest trolig att söka hundra jobb och tacka nej till alla?",
  "Vem är mest trolig att komma försent till sin egen anställningsintervju?",
  "Vem är mest trolig att charma sig igenom en intervju utan att kunna något?",
  "Vem är mest trolig att bli politiker?",
  "Vem är mest trolig att bli rektor på sin gamla skola?",
  "Vem är mest trolig att skriva en bok om sitt liv?",
  "Vem är mest trolig att bli professor?",
  "Vem är mest trolig att hoppa av en utbildning två veckor innan examen?",
  "Vem är mest trolig att plugga vidare vid 50?",
  "Vem är mest trolig att bli hantverkare med guldläge i schemat?",
  "Vem är mest trolig att flytta utomlands för jobbet?",
  "Vem är mest trolig att tacka nej till drömjobb för att slippa flytta?",
  "Vem är mest trolig att bli sin egen chef för att slippa alla andra chefer?",
  "Vem är mest trolig att ha snyggast CV men sämst arbetsmoral?",
  "Vem är mest trolig att jobba dubbla skift utan att klaga?",
  "Vem är mest trolig att starta en podd om pengar?",
  "Vem är mest trolig att bli sponsrad influencer?",
  "Vem är mest trolig att sälja allt de äger och börja om?",
  "Vem är mest trolig att köpa en sommarstuga innan lägenhet?",
  "Vem är mest trolig att samla på något som blir värt miljoner?",
  "Vem är mest trolig att slänga något som visar sig vara värt miljoner?",
  "Vem är mest trolig att bli rik på en app-idé de fick på fyllan?",
  "Vem är mest trolig att patentera en uppfinning?",
  "Vem är mest trolig att vinna en rättstvist mot ett storbolag?",
  "Vem är mest trolig att bli granskad av Skatteverket?",
  "Vem är mest trolig att deklarera i sista sekunden varje år?",
  "Vem är mest trolig att ha ordning på kvitton från 2015?",
  "Vem är mest trolig att öppna en restaurang?",
  "Vem är mest trolig att öppna ett gym?",
  "Vem är mest trolig att bli mäklare med egna bussreklamer?",
  "Vem är mest trolig att bli lärare som eleverna älskar?",
  "Vem är mest trolig att bli polis?",
  "Vem är mest trolig att bli brandman?",
  "Vem är mest trolig att jobba med något som inte finns än?",
  "Vem är mest trolig att bli chef och genast bli maktgalen?",
  "Vem är mest trolig att vägra befordran för att slippa ansvar?",
  "Vem är mest trolig att starta fackklubb på jobbet?",
  "Vem är mest trolig att vinna 'årets nykomling' var de än börjar?",
  "Vem är mest trolig att ha en hemlig sparbössa med kontanter?",
  "Vem är mest trolig att köpa kryptovaluta på topp och hålla i tio år av princip?",
  "Vem är mest trolig att bli bostadsrättsföreningens ordförande?",
  "Vem är mest trolig att engagera sig i grannfejden om häcken?",
  "Vem är mest trolig att vinna en budgivning av ren envishet?",
  "Vem är mest trolig att köpa lägenhet osedd?",
  "Vem är mest trolig att hyra ut sitt vardagsrum för extrapengar?",
  "Vem är mest trolig att ha tre jobb samtidigt utan att någon vet?",
  "Vem är mest trolig att gå i pension och genast starta nytt företag?",
  "Vem är mest trolig att bli den rikaste i rummet utan att någonsin skryta?",
  "Vem är mest trolig att skryta om pengar de inte har?",
  "Vem är mest trolig att bli upptäckt som dold mattesnille på jobbet?",
];

const PINSAMT_OCH_VARDAG = [
  "Vem är mest trolig att glömma sin egen födelsedag?",
  "Vem är mest trolig att äta något från golvet?",
  "Vem är mest trolig att skratta på en begravning?",
  "Vem är mest trolig att vinka tillbaka till någon som vinkade åt någon annan?",
  "Vem är mest trolig att fastna i en rulltrappa på något vis?",
  "Vem är mest trolig att låsa sig ute i bara morgonrock?",
  "Vem är mest trolig att svara 'du med' när kyparen säger smaklig måltid?",
  "Vem är mest trolig att gå in i en lyktstolpe medan de kollar mobilen?",
  "Vem är mest trolig att skicka ett skärmklipp till personen det handlar om?",
  "Vem är mest trolig att glömma namnet på någon de känt i åratal?",
  "Vem är mest trolig att kalla läraren för mamma?",
  "Vem är mest trolig att snubbla uppför en trappa?",
  "Vem är mest trolig att fastna med jackan i en dörr?",
  "Vem är mest trolig att prata högt för sig själv på stan?",
  "Vem är mest trolig att bli fast i småprat med grannen i en timme?",
  "Vem är mest trolig att låtsas prata i telefon för att slippa folk?",
  "Vem är mest trolig att gå på fel buss och åka med ändå?",
  "Vem är mest trolig att somna på tåget och missa sin station?",
  "Vem är mest trolig att glömma var de parkerat bilen?",
  "Vem är mest trolig att leta efter mobilen medan de pratar i den?",
  "Vem är mest trolig att ha solglasögonen på huvudet medan de letar efter dem?",
  "Vem är mest trolig att komma en timme fel på grund av tidsomställningen?",
  "Vem är mest trolig att gratulera någon på fel dag?",
  "Vem är mest trolig att svara på en retorisk fråga?",
  "Vem är mest trolig att räcka upp handen på ett jobbmöte?",
  "Vem är mest trolig att spilla kaffe på sig själv före ett viktigt möte?",
  "Vem är mest trolig att ha tröjan ut och in en hel dag?",
  "Vem är mest trolig att gå med spenat mellan tänderna utan att någon säger något?",
  "Vem är mest trolig att nysa så högt att hela rummet hoppar till?",
  "Vem är mest trolig att skratta i fel ögonblick på bio?",
  "Vem är mest trolig att applådera när planet landar?",
  "Vem är mest trolig att fastna i tullen för en glömd banan i väskan?",
  "Vem är mest trolig att tappa brickan i skolmatsalen inför alla?",
  "Vem är mest trolig att säga 'jag älskar dig' av misstag till sin chef?",
  "Vem är mest trolig att trycka på dörrar där det står 'drag'?",
  "Vem är mest trolig att stå i fel kö i tjugo minuter?",
  "Vem är mest trolig att beställa samma sak som personen före av ren panik?",
  "Vem är mest trolig att glömma pinkoden till sin egen ytterdörr?",
  "Vem är mest trolig att vattna en plastväxt i månader?",
  "Vem är mest trolig att döda en kaktus?",
  "Vem är mest trolig att ha 74 olästa röstmeddelanden?",
  "Vem är mest trolig att svara 'ja' utan att ha hört frågan?",
  "Vem är mest trolig att skicka 'hej hej' och sedan glömma vad de skulle säga?",
  "Vem är mest trolig att gå till affären för en sak och glömma just den saken?",
  "Vem är mest trolig att frysa fast tungan på metall som vuxen?",
  "Vem är mest trolig att bränna sig på 'varning het yta'?",
  "Vem är mest trolig att testa om färgen verkligen är våt?",
  "Vem är mest trolig att sätta på tvättmaskinen utan tvätt i?",
  "Vem är mest trolig att diska en gaffel i tio minuter medan de pratar?",
  "Vem är mest trolig att ha ett skåp som allt rasar ur när man öppnar?",
  "Vem är mest trolig att stryka en skjorta och bränna hål i den?",
  "Vem är mest trolig att låsa in nycklarna i bilen med motorn igång?",
  "Vem är mest trolig att tanka fel bränsle?",
  "Vem är mest trolig att köra vilse trots GPS?",
  "Vem är mest trolig att backa in i en soptunna på uppfarten?",
  "Vem är mest trolig att få parkeringsböter tre gånger samma vecka?",
  "Vem är mest trolig att bli fartblind på en elsparkcykel?",
  "Vem är mest trolig att ramla av en stillastående cykel?",
  "Vem är mest trolig att gå emot en glasruta de trodde var en dörr?",
  "Vem är mest trolig att säga hej till en skyltdocka?",
  "Vem är mest trolig att be en staty om ursäkt?",
  "Vem är mest trolig att klappa en hund och ignorera dess ägare helt?",
  "Vem är mest trolig att prata bebisspråk med alla djur de ser?",
  "Vem är mest trolig att glömma sitt paraply överallt?",
  "Vem är mest trolig att äga femton likadana svarta tröjor?",
  "Vem är mest trolig att ha strumpor som aldrig matchar?",
  "Vem är mest trolig att gå hemifrån i tofflor av misstag?",
  "Vem är mest trolig att upptäcka prislappen kvar på kläderna mitt på dagen?",
  "Vem är mest trolig att använda fel namn på någons partner i ett år?",
  "Vem är mest trolig att avsluta ett samtal med 'puss' till hantverkaren?",
  "Vem är mest trolig att vinka hejdå och sedan gå åt samma håll?",
  "Vem är mest trolig att fastna i ett evigt 'efter dig'-moment i en dörr?",
  "Vem är mest trolig att skratta så de sätter maten i halsen?",
  "Vem är mest trolig att berätta samma historia för tredje gången samma kväll?",
  "Vem är mest trolig att glömma poängen mitt i sin egen historia?",
  "Vem är mest trolig att viska så högt att alla hör?",
  "Vem är mest trolig att råka gilla en fem år gammal bild vid stalkande?",
  "Vem är mest trolig att skicka ett meddelande till fel gruppchatt?",
  "Vem är mest trolig att ha mobilen på högsta volym på bio?",
  "Vem är mest trolig att glömma stänga av micken på videomöte?",
  "Vem är mest trolig att ha kameran på utan att veta det på mötet?",
  "Vem är mest trolig att svara 'du också' när piloten önskar trevlig resa?",
  "Vem är mest trolig att tappa alla papper i en vindpust?",
  "Vem är mest trolig att sätta sig på sina egna glasögon?",
  "Vem är mest trolig att leta i hela huset efter nycklarna som satt i dörren?",
  "Vem är mest trolig att missa sitt eget namn när det ropas upp?",
  "Vem är mest trolig att gå till fel lokal på ett släktkalas?",
  "Vem är mest trolig att klä ut sig till fel tema på en fest?",
  "Vem är mest trolig att vara den enda utklädda på en vanlig fest?",
  "Vem är mest trolig att komma i samma outfit som någon annan och vägra byta?",
  "Vem är mest trolig att tappa mobilen i toaletten?",
  "Vem är mest trolig att tappa glassen i marken direkt efter köp?",
  "Vem är mest trolig att bita sig i tungan mitt i en viktig mening?",
  "Vem är mest trolig att få hicka under tyst minut?",
  "Vem är mest trolig att börja skratta av nervositet i värsta läget?",
  "Vem är mest trolig att vända hem tre gånger för att kolla om dörren är låst?",
  "Vem är mest trolig att öppna kylskåpet fem gånger utan att ta något?",
  "Vem är mest trolig att glömma i duschen om de tvättat håret?",
  "Vem är mest trolig att svara 'lika mycket klockan' istället för tack?",
  "Vem är mest trolig att bära alla matkassar i en vända oavsett kostnad?",
];

const FRAMTID_OCH_LIVET = [
  "Vem är mest trolig att bli president?",
  "Vem är mest trolig att flytta utomlands?",
  "Vem är mest trolig att bli känd på sociala medier?",
  "Vem är mest trolig att bli statsminister?",
  "Vem är mest trolig att hamna i en dokumentär?",
  "Vem är mest trolig att bli omskriven i historieböckerna?",
  "Vem är mest trolig att bli hundra år gammal?",
  "Vem är mest trolig att flytta tillbaka till sin hemort?",
  "Vem är mest trolig att bo kvar i samma lägenhet i 40 år?",
  "Vem är mest trolig att flytta tio gånger på tio år?",
  "Vem är mest trolig att bli den coola morbrodern eller mostern?",
  "Vem är mest trolig att skaffa fem barn?",
  "Vem är mest trolig att skaffa fem hundar istället för barn?",
  "Vem är mest trolig att bli den stränga föräldern?",
  "Vem är mest trolig att bli föräldern som är barnens kompis?",
  "Vem är mest trolig att uppfostra en framtida OS-vinnare?",
  "Vem är mest trolig att bli farmor eller morfar som skämmer bort värst?",
  "Vem är mest trolig att bli granne med någon i det här sällskapet?",
  "Vem är mest trolig att bo i kollektiv vid 60?",
  "Vem är mest trolig att köpa en gård och bli självförsörjande?",
  "Vem är mest trolig att skaffa höns på balkongen?",
  "Vem är mest trolig att bli vegetarian över en natt?",
  "Vem är mest trolig att bli vegan och prata om det jämt?",
  "Vem är mest trolig att gå med i en konstig klubb?",
  "Vem är mest trolig att bli ordförande i villaföreningen?",
  "Vem är mest trolig att engagera sig politiskt på gamla dar?",
  "Vem är mest trolig att kedja fast sig vid ett träd i protest?",
  "Vem är mest trolig att skriva insändare varje vecka?",
  "Vem är mest trolig att ringa radion och klaga live?",
  "Vem är mest trolig att vinna en lokal tävling och rama in diplomet?",
  "Vem är mest trolig att bli hedersmedborgare i sin hemkommun?",
  "Vem är mest trolig att få en gata uppkallad efter sig?",
  "Vem är mest trolig att bli intervjuad på stan och säga något viralt?",
  "Vem är mest trolig att vara med i en gameshow på TV?",
  "Vem är mest trolig att vinna en gameshow på TV?",
  "Vem är mest trolig att söka till en dokusåpa i hemlighet?",
  "Vem är mest trolig att bli utröstad först ur en dokusåpa?",
  "Vem är mest trolig att vinna hela dokusåpan?",
  "Vem är mest trolig att bli programledare?",
  "Vem är mest trolig att bli ståuppkomiker?",
  "Vem är mest trolig att skriva en självbiografi som blir film?",
  "Vem är mest trolig att spela huvudrollen i sitt eget liv lite för mycket?",
  "Vem är mest trolig att bli morgonmänniska på riktigt?",
  "Vem är mest trolig att aldrig någonsin bli en morgonmänniska?",
  "Vem är mest trolig att gå i terapi och rekommendera det till alla?",
  "Vem är mest trolig att bli yogalärare?",
  "Vem är mest trolig att flytta till ett kloster ett år?",
  "Vem är mest trolig att klättra Kilimanjaro på semestern?",
  "Vem är mest trolig att springa ett maraton på varje kontinent?",
  "Vem är mest trolig att skriva testamente vid 30?",
  "Vem är mest trolig att planera sin egen begravning i detalj?",
  "Vem är mest trolig att bli den som håller ihop gänget om 20 år?",
  "Vem är mest trolig att ordna återträffen om 25 år?",
  "Vem är mest trolig att glömma bort återträffen de själva ordnade?",
  "Vem är mest trolig att bli rikast i klassen enligt gamla klasskamrater?",
  "Vem är mest trolig att se exakt likadan ut om 30 år?",
  "Vem är mest trolig att bli grå i håret först och äga det?",
  "Vem är mest trolig att skaffa tatuering efter 50?",
  "Vem är mest trolig att ta körkort sist av alla?",
  "Vem är mest trolig att köpa motorcykel i medelålderskris?",
  "Vem är mest trolig att köpa husbil och åka jorden runt?",
  "Vem är mest trolig att gifta om sig flest gånger?",
  "Vem är mest trolig att fira nyår på en ny plats varje år?",
  "Vem är mest trolig att fira jul exakt likadant i 50 år?",
  "Vem är mest trolig att bli släktens historieberättare?",
  "Vem är mest trolig att göra släktforskning och hitta något chockerande?",
  "Vem är mest trolig att ärva något helt oväntat?",
  "Vem är mest trolig att bli miljonär först och pank först?",
  "Vem är mest trolig att uppfinna något som alla använder?",
  "Vem är mest trolig att bli professor i något udda ämne?",
  "Vem är mest trolig att doktorera bara för titelns skull?",
  "Vem är mest trolig att lära sig fem språk?",
  "Vem är mest trolig att glömma sitt modersmål utomlands på två år?",
  "Vem är mest trolig att bli väderpresentatör?",
  "Vem är mest trolig att bli astronaut om chansen fanns?",
  "Vem är mest trolig att tacka nej till en rymdresa av bekvämlighet?",
  "Vem är mest trolig att överleva längst i en zombieapokalyps?",
  "Vem är mest trolig att åka fast först i en zombieapokalyps?",
  "Vem är mest trolig att bygga ett skyddsrum i trädgården?",
  "Vem är mest trolig att ha en packlista för världens undergång?",
  "Vem är mest trolig att vinna en överlevnadstävling i vildmarken?",
  "Vem är mest trolig att ge upp efter en natt i tält?",
  "Vem är mest trolig att bli eremit i skogen?",
  "Vem är mest trolig att starta en sekt av misstag?",
  "Vem är mest trolig att gå med i en bokklubb och ta över den?",
  "Vem är mest trolig att lära sig spela instrument efter 40?",
  "Vem är mest trolig att starta band med sina barn?",
  "Vem är mest trolig att bli lokal legend på karaokebaren?",
  "Vem är mest trolig att skriva en låt som fastnar på radio?",
  "Vem är mest trolig att vinna en melodifestival?",
  "Vem är mest trolig att bli konstnär på äldre dar?",
  "Vem är mest trolig att sälja en tavla för mer än den borde kosta?",
  "Vem är mest trolig att bli samlare av något väldigt nischat?",
  "Vem är mest trolig att ha ett museum hemma i garaget?",
  "Vem är mest trolig att donera allt till välgörenhet?",
  "Vem är mest trolig att starta en stiftelse i sitt namn?",
  "Vem är mest trolig att bli ihågkommen för sin godhet?",
  "Vem är mest trolig att bli ihågkommen för sina upptåg?",
  "Vem är mest trolig att leva precis det liv de drömde om som barn?",
];

const SPORT_OCH_HALSA = [
  "Vem är mest trolig att hamna i slagsmål för något löjligt?",
  "Vem är mest trolig att springa maraton utan att träna?",
  "Vem är mest trolig att köpa gymkort och gå två gånger?",
  "Vem är mest trolig att bli personlig tränare?",
  "Vem är mest trolig att vinna en armbrytning mot alla i rummet?",
  "Vem är mest trolig att skada sig på uppvärmningen?",
  "Vem är mest trolig att bli proffs i en sport ingen hört talas om?",
  "Vem är mest trolig att skrika högst på sina barns matcher?",
  "Vem är mest trolig att bli utvisad som lagledare?",
  "Vem är mest trolig att starta gräl med domaren?",
  "Vem är mest trolig att fejka en skada för att slippa förlora?",
  "Vem är mest trolig att vinna guld i mästerskap i tv-soffan?",
  "Vem är mest trolig att kunna alla spelares statistik utantill?",
  "Vem är mest trolig att gråta när laget åker ur?",
  "Vem är mest trolig att byta favoritlag när det går dåligt?",
  "Vem är mest trolig att ha samma lag hela livet trots allt?",
  "Vem är mest trolig att åka på bortamatch i ett annat land?",
  "Vem är mest trolig att bli bäst i gänget på padel?",
  "Vem är mest trolig att slå sönder ett racket i frustration?",
  "Vem är mest trolig att utmana någon på tennis och förlora 6-0?",
  "Vem är mest trolig att vinna guldboll i korpen?",
  "Vem är mest trolig att göra självmål i en viktig match?",
  "Vem är mest trolig att rädda matchen på övertid?",
  "Vem är mest trolig att bli vald sist i alla lagsporter men vinna ändå?",
  "Vem är mest trolig att cykla till jobbet i snöstorm?",
  "Vem är mest trolig att köpa dyraste cykeln och aldrig cykla?",
  "Vem är mest trolig att vinna ett triathlon?",
  "Vem är mest trolig att anmäla sig till triathlon och bara simma?",
  "Vem är mest trolig att gå vilse på en joggingrunda?",
  "Vem är mest trolig att springa fortast till bussen?",
  "Vem är mest trolig att ta trapporna av princip?",
  "Vem är mest trolig att ta hissen en våning?",
  "Vem är mest trolig att räkna promenaden till kylskåpet som träning?",
  "Vem är mest trolig att bli yogainstruktör på Bali?",
  "Vem är mest trolig att somna på avslappningen i yogan?",
  "Vem är mest trolig att köpa all träningsutrustning som finns på reklam?",
  "Vem är mest trolig att ha ett hemmagym som samlar damm?",
  "Vem är mest trolig att slå personbästa varje vecka?",
  "Vem är mest trolig att ljuga om sitt personbästa?",
  "Vem är mest trolig att bli vegan för sporten och avsluta med kebab?",
  "Vem är mest trolig att dricka proteinshake till frukost, lunch och middag?",
  "Vem är mest trolig att räkna kalorier på semestern?",
  "Vem är mest trolig att starta en hälsoblogg?",
  "Vem är mest trolig att prova varje ny dietfluga?",
  "Vem är mest trolig att hålla nyårslöftet om träning hela året?",
  "Vem är mest trolig att bryta nyårslöftet den 2 januari?",
  "Vem är mest trolig att gå upp klockan fem för att träna?",
  "Vem är mest trolig att boka träningspass och sova igenom det?",
  "Vem är mest trolig att bli bäst i gänget på golf?",
  "Vem är mest trolig att kasta klubban i vattnet på golfbanan?",
  "Vem är mest trolig att få hole-in-one och prata om det i tio år?",
  "Vem är mest trolig att vinna bowlingkvällen med skruvteknik?",
  "Vem är mest trolig att kasta klot i rännan varje gång och skylla på skorna?",
  "Vem är mest trolig att bli dartproffs på puben?",
  "Vem är mest trolig att träffa väggen istället för darttavlan?",
  "Vem är mest trolig att vinna armhävningstävlingen?",
  "Vem är mest trolig att utmana på armhävningar och ge upp vid tre?",
  "Vem är mest trolig att klättra på allt som går att klättra på?",
  "Vem är mest trolig att fastna i klätterväggen och behöva hjälp ner?",
  "Vem är mest trolig att hoppa fallskärm frivilligt?",
  "Vem är mest trolig att ångra sig i planet med fallskärmen på?",
  "Vem är mest trolig att testa bungyjump utan att tveka?",
  "Vem är mest trolig att bli surfare på heltid?",
  "Vem är mest trolig att stå upp på surfbrädan första försöket?",
  "Vem är mest trolig att åka skidor utför svartaste backen direkt?",
  "Vem är mest trolig att ta lift ner för att backen såg läskig ut?",
  "Vem är mest trolig att bli fastande i skidliften med skräck för höjder?",
  "Vem är mest trolig att vinna afterski-dansen?",
  "Vem är mest trolig att bada isvak varje vinter?",
  "Vem är mest trolig att vägra bada under 25 grader i vattnet?",
  "Vem är mest trolig att simma längst ut på badet?",
  "Vem är mest trolig att bli livräddare?",
  "Vem är mest trolig att vinna simtävlingen på semestern?",
  "Vem är mest trolig att göra magplask från trampolinen?",
  "Vem är mest trolig att bli bäst på minigolf av ren tur?",
  "Vem är mest trolig att föra protokoll i minigolf med domarambitioner?",
  "Vem är mest trolig att bli schackmästare?",
  "Vem är mest trolig att välta brädet när de förlorar i schack?",
  "Vem är mest trolig att vinna varje sällskapsspel de rör?",
  "Vem är mest trolig att bli osams på riktigt över Monopol?",
  "Vem är mest trolig att fuska i Fia med knuff?",
  "Vem är mest trolig att bli e-sportproffs?",
  "Vem är mest trolig att kasta handkontrollen i väggen?",
  "Vem är mest trolig att vinna gokart-tävlingen?",
  "Vem är mest trolig att bli varnad i gokart för vårdslös körning?",
  "Vem är mest trolig att vinna en dansbattle nykter?",
  "Vem är mest trolig att gå på styrketräning i jeans?",
  "Vem är mest trolig att glömma gymkläderna och träna i arbetskläder?",
  "Vem är mest trolig att bli massör?",
  "Vem är mest trolig att somna hos massören?",
  "Vem är mest trolig att prova kallbad och bli frälst?",
  "Vem är mest trolig att köra ultramaraton av ren envishet?",
  "Vem är mest trolig att vinna gruppens stegtävling med fusksteg?",
  "Vem är mest trolig att skaka mobilen för att samla steg?",
  "Vem är mest trolig att bli hälsokostexpert utan utbildning?",
  "Vem är mest trolig att äta en chilipeppar på utmaning?",
  "Vem är mest trolig att gråta av en mild salsa?",
  "Vem är mest trolig att vinna en varmkorvsätartävling?",
  "Vem är mest trolig att bli tränare för barnens lag och ta det på för stort allvar?",
  "Vem är mest trolig att göra hela gruppen till sitt eget träningsprojekt?",
];

const MAT_OCH_DRYCK = [
  "Vem är mest trolig att beställa samma rätt på varje restaurang?",
  "Vem är mest trolig att bli kock i ett eget program?",
  "Vem är mest trolig att bränna vidbränt ris tre gånger i rad?",
  "Vem är mest trolig att sätta eld på köket med en toast?",
  "Vem är mest trolig att äta frukost till middag varje dag?",
  "Vem är mest trolig att ha ketchup på allt?",
  "Vem är mest trolig att beställa extra allt, alltid?",
  "Vem är mest trolig att vinna en grilltävling?",
  "Vem är mest trolig att bränna korven och kalla det 'krispig'?",
  "Vem är mest trolig att bli sommelier?",
  "Vem är mest trolig att låtsas känna smaker på vinprovning?",
  "Vem är mest trolig att välja vin efter etiketten?",
  "Vem är mest trolig att bli baristanörd med våg och timer?",
  "Vem är mest trolig att dricka sju koppar kaffe om dagen?",
  "Vem är mest trolig att sluta med kaffe och prata om det jämt?",
  "Vem är mest trolig att baka surdegsbröd och döpa degen?",
  "Vem är mest trolig att glömma degen och hitta den en vecka senare?",
  "Vem är mest trolig att vinna ett bakprogram på TV?",
  "Vem är mest trolig att köpa tårta och säga att den är hemmagjord?",
  "Vem är mest trolig att äta upp allas rester på restaurangen?",
  "Vem är mest trolig att beställa dessert först?",
  "Vem är mest trolig att äta efterrätt före maten av princip?",
  "Vem är mest trolig att smaka på allas tallrikar utan att fråga?",
  "Vem är mest trolig att vakta sin tallrik som en hök?",
  "Vem är mest trolig att bli hangry och förneka det?",
  "Vem är mest trolig att alltid ha snacks i väskan?",
  "Vem är mest trolig att äta hela chipspåsen innan filmen börjat?",
  "Vem är mest trolig att gömma godis för sig själv hemma?",
  "Vem är mest trolig att bjuda på godis men bara de smaker de inte gillar?",
  "Vem är mest trolig att äta tacos varje fredag hela livet?",
  "Vem är mest trolig att göra egen taco-krydda och kalla den hemlig?",
  "Vem är mest trolig att sätta ananas på pizzan och stå för det?",
  "Vem är mest trolig att starta bråk om ananas på pizza?",
  "Vem är mest trolig att beställa pizza till frukost?",
  "Vem är mest trolig att äta kebabpizza i tre länder?",
  "Vem är mest trolig att bli stammis med egen hylla på ett fik?",
  "Vem är mest trolig att känna alla på den lokala restaurangen vid namn?",
  "Vem är mest trolig att lämna dricks fast det blev fel?",
  "Vem är mest trolig att klaga på maten men äta upp allt?",
  "Vem är mest trolig att skicka tillbaka en rätt tre gånger?",
  "Vem är mest trolig att äta världens starkaste chili frivilligt?",
  "Vem är mest trolig att beställa barnmeny som vuxen?",
  "Vem är mest trolig att äta samma frukost i tjugo år?",
  "Vem är mest trolig att prova insekter som proteinkälla?",
  "Vem är mest trolig att bli matfotograf som aldrig äter varm mat?",
  "Vem är mest trolig att fota maten innan någon får äta?",
  "Vem är mest trolig att göra matlåda av festbuffén?",
  "Vem är mest trolig att ta sista biten utan att fråga?",
  "Vem är mest trolig att dela sista biten i exakt lika delar?",
  "Vem är mest trolig att äta upp tårtbiten som var sparad till någon annan?",
  "Vem är mest trolig att göra världens bästa pannkakor?",
  "Vem är mest trolig att vända pannkakan i luften och tappa den?",
  "Vem är mest trolig att koka pastan tills den blir gröt?",
  "Vem är mest trolig att salta maten innan de smakat?",
  "Vem är mest trolig att ha en kryddhylla i bokstavsordning?",
  "Vem är mest trolig att använda vitlök i dubbla mängder alltid?",
  "Vem är mest trolig att odla egna tomater på balkongen?",
  "Vem är mest trolig att döpa sina kryddväxter?",
  "Vem är mest trolig att bli svampexpert och våga plocka allt?",
  "Vem är mest trolig att plocka svamp och inte våga äta någon?",
  "Vem är mest trolig att fiska sin egen middag?",
  "Vem är mest trolig att köpa fisk och säga att de fångat den?",
  "Vem är mest trolig att bli grillmästaren som ingen får hjälpa?",
  "Vem är mest trolig att göra upp eld utan tändare?",
  "Vem är mest trolig att ta med sig egen sås till restaurangen?",
  "Vem är mest trolig att ha starkast åsikter om potatismos?",
  "Vem är mest trolig att välja restaurang i en timme och sedan ta pizza?",
  "Vem är mest trolig att svara 'vet inte, vad vill du äta?' i en evighet?",
  "Vem är mest trolig att laga mat till tolv fast de är fyra?",
  "Vem är mest trolig att bjuda på middag och beställa hem mat i smyg?",
  "Vem är mest trolig att äta middag klockan fem som en pensionär?",
  "Vem är mest trolig att äta middag klockan elva på kvällen?",
  "Vem är mest trolig att dricka mjölk till all mat?",
  "Vem är mest trolig att blanda alla läsksorter i samma glas?",
  "Vem är mest trolig att dricka smoothie i alla färger utom god?",
  "Vem är mest trolig att göra juice på allt som finns hemma?",
  "Vem är mest trolig att köpa hela kryddhyllan på semestern?",
  "Vem är mest trolig att ta hem ost från varje resa?",
  "Vem är mest trolig att bli osthandlare?",
  "Vem är mest trolig att äta ost till efterrätt av princip?",
  "Vem är mest trolig att beställa in hela menyn för att 'testa'?",
  "Vem är mest trolig att äta buffé tills personalen tittar?",
  "Vem är mest trolig att gå tillbaka till buffén en sjätte gång?",
  "Vem är mest trolig att smuggla in eget godis på bio?",
  "Vem är mest trolig att äta popcornen innan reklamen är slut?",
  "Vem är mest trolig att beställa störst popcorn och vakta dem?",
  "Vem är mest trolig att alltid veta var närmsta korvkiosk finns?",
  "Vem är mest trolig att recensera varje kebabställe i stan?",
  "Vem är mest trolig att starta en foodtruck?",
  "Vem är mest trolig att uppfinna en ny maträtt av rester?",
  "Vem är mest trolig att äta något med utgånget datum och chansa?",
  "Vem är mest trolig att lukta på mjölken och ändå fråga någon annan?",
  "Vem är mest trolig att ha en frys full med matlådor märkta med datum?",
  "Vem är mest trolig att ha en frys full med omärkta mysterielådor?",
  "Vem är mest trolig att göra världens starkaste egna hotsauce?",
  "Vem är mest trolig att äta glass mitt i vintern?",
  "Vem är mest trolig att beställa tolv kulor glass och ångra inget?",
  "Vem är mest trolig att bli bartender med egna signaturdrinkar?",
  "Vem är mest trolig att skåla i vatten och hålla längsta talet?",
];

const TEKNIK_OCH_SOME = [
  "Vem är mest trolig att bli viral av fel anledning?",
  "Vem är mest trolig att ha över tusen olästa mejl?",
  "Vem är mest trolig att ha inkorgen på noll varje dag?",
  "Vem är mest trolig att svara på sms tre veckor senare?",
  "Vem är mest trolig att svara innan man hunnit skicka klart?",
  "Vem är mest trolig att bli influencer på riktigt?",
  "Vem är mest trolig att starta en kanal som får tre visningar?",
  "Vem är mest trolig att bli AI:ns bästa vän?",
  "Vem är mest trolig att bråka med en chatbot?",
  "Vem är mest trolig att bli lurad av en nätbedragare?",
  "Vem är mest trolig att genomskåda alla bluffmejl direkt?",
  "Vem är mest trolig att använda samma lösenord överallt?",
  "Vem är mest trolig att glömma alla sina lösenord varje vecka?",
  "Vem är mest trolig att ha 400 flikar öppna samtidigt?",
  "Vem är mest trolig att ha skärmsprickan kvar i två år?",
  "Vem är mest trolig att köpa varje ny telefon på releasedagen?",
  "Vem är mest trolig att ha kvar sin telefon i åtta år?",
  "Vem är mest trolig att tappa telefonen i vattnet på semestern?",
  "Vem är mest trolig att ha 2% batteri jämt?",
  "Vem är mest trolig att bära med sig powerbank överallt?",
  "Vem är mest trolig att scrolla tills klockan tre på natten?",
  "Vem är mest trolig att kolla mobilen mitt i en film på bio?",
  "Vem är mest trolig att lägga ut allt de äter?",
  "Vem är mest trolig att lägga ut en story från gymmet varje dag?",
  "Vem är mest trolig att aldrig lägga ut något men se allt?",
  "Vem är mest trolig att kommentera fel på en kändis inlägg?",
  "Vem är mest trolig att råka sända live utan att veta det?",
  "Vem är mest trolig att bli meme i gruppchatten?",
  "Vem är mest trolig att skicka gamla memes som nyheter?",
  "Vem är mest trolig att svara med bara emojis i en vecka?",
  "Vem är mest trolig att använda tummen upp-emoji till allt?",
  "Vem är mest trolig att skriva romaner i gruppchatten?",
  "Vem är mest trolig att lämna gruppchatten i protest och komma tillbaka?",
  "Vem är mest trolig att muta gruppchatten i ett år?",
  "Vem är mest trolig att starta en ny gruppchatt för varje ämne?",
  "Vem är mest trolig att byta profilbild en gång per decennium?",
  "Vem är mest trolig att ha en selfie som profilbild från 2014?",
  "Vem är mest trolig att fota allt i sämsta möjliga vinkel?",
  "Vem är mest trolig att ha 40 000 bilder och noll ordning?",
  "Vem är mest trolig att redigera en bild i en timme innan publicering?",
  "Vem är mest trolig att radera inlägg som får för få likes?",
  "Vem är mest trolig att gilla sina egna inlägg?",
  "Vem är mest trolig att bli blockad av en kändis?",
  "Vem är mest trolig att få svar av en kändis och rama in det?",
  "Vem är mest trolig att starta poddcast om sitt eget liv?",
  "Vem är mest trolig att lyssna på poddar i dubbel hastighet?",
  "Vem är mest trolig att bli programmerare självlärd?",
  "Vem är mest trolig att bygga ett smart hem som ingen förstår?",
  "Vem är mest trolig att prata med sin röstassistent som en vän?",
  "Vem är mest trolig att skrika på sin röstassistent?",
  "Vem är mest trolig att ha robotdammsugare med namn?",
  "Vem är mest trolig att beställa saker på nätet i sömnen?",
  "Vem är mest trolig att handla på nätet efter midnatt och ångra allt?",
  "Vem är mest trolig att glömma att avsluta gratisprenumerationer?",
  "Vem är mest trolig att betala för tolv streamingtjänster?",
  "Vem är mest trolig att låna allas konton utan att betala något?",
  "Vem är mest trolig att se en hel serie på en helg?",
  "Vem är mest trolig att somna fem minuter in i varje film?",
  "Vem är mest trolig att spoila slutet för alla?",
  "Vem är mest trolig att vägra se trailern för att undvika spoilers?",
  "Vem är mest trolig att spela mobilspel på möten?",
  "Vem är mest trolig att köpa saker i mobilspel för riktiga pengar?",
  "Vem är mest trolig att bli bäst i gänget på alla tv-spel?",
  "Vem är mest trolig att skylla på kontrollen varje gång de förlorar?",
  "Vem är mest trolig att streama sitt spelande inför noll tittare?",
  "Vem är mest trolig att bygga en gaming-setup dyrare än bilen?",
  "Vem är mest trolig att fastna i videosamtal med frusen bild i pinsam min?",
  "Vem är mest trolig att säga 'ni hör mig inte, min mick är död' dagligen?",
  "Vem är mest trolig att ringa videosamtal från konstigast plats?",
  "Vem är mest trolig att ha ett skrivbord fullt av kablar ingen vågar röra?",
  "Vem är mest trolig att fixa allas tekniska problem på släktträffar?",
  "Vem är mest trolig att starta om routern som lösning på allt?",
  "Vem är mest trolig att läsa manualen först av alla?",
  "Vem är mest trolig att slänga manualen och montera fel?",
  "Vem är mest trolig att ha en smartklocka och lyda alla dess order?",
  "Vem är mest trolig att gå i cirklar för att stänga aktivitetsringarna?",
  "Vem är mest trolig att mäta sömnen och bli stressad av resultatet?",
  "Vem är mest trolig att uppdatera aldrig någonting av rädsla?",
  "Vem är mest trolig att trycka 'uppdatera senare' i tre år?",
  "Vem är mest trolig att förlora allt för att de aldrig tog backup?",
  "Vem är mest trolig att ha tre backuper av allt?",
  "Vem är mest trolig att skriva krönikor i kommentarsfält?",
  "Vem är mest trolig att vinna en nätdiskussion genom uthållighet?",
  "Vem är mest trolig att googla symptom och boka begravning?",
  "Vem är mest trolig att googla svaret mitt i en frågesport?",
  "Vem är mest trolig att bli utsedd till gruppchattens faktagranskare?",
  "Vem är mest trolig att skicka artiklar ingen läser?",
  "Vem är mest trolig att tro på allt de läser på nätet?",
  "Vem är mest trolig att bli nätdetektiv och lösa ett riktigt fall?",
  "Vem är mest trolig att hitta vem som helst på nätet på fem minuter?",
  "Vem är mest trolig att råka avslöja en överraskning i gruppchatten?",
  "Vem är mest trolig att skriva 'grattis' på fel persons vägg?",
  "Vem är mest trolig att sälja saker på nätet och aldrig skicka dem?",
  "Vem är mest trolig att köpa något begagnat som aldrig funkar?",
  "Vem är mest trolig att bli lurad på en nätauktion om en enkrona?",
  "Vem är mest trolig att vinna en budgivning på något de inte ville ha?",
  "Vem är mest trolig att fota mat innan alla får äta — och den blir suddig?",
  "Vem är mest trolig att ha flest följare om fem år?",
  "Vem är mest trolig att radera alla sociala medier och må bäst av alla?",
  "Vem är mest trolig att komma på appen som förändrar allt?",
];

const RESOR_OCH_AVENTYR = [
  "Vem är mest trolig att bli stoppad i tullen?",
  "Vem är mest trolig att missa flyget för att de fikade?",
  "Vem är mest trolig att vara på flygplatsen fem timmar för tidigt?",
  "Vem är mest trolig att packa väskan en timme innan avgång?",
  "Vem är mest trolig att packa en månad i förväg med lista?",
  "Vem är mest trolig att glömma passet hemma?",
  "Vem är mest trolig att tappa passet utomlands?",
  "Vem är mest trolig att boka resa till fel stad med samma namn?",
  "Vem är mest trolig att flytta till en öde ö frivilligt?",
  "Vem är mest trolig att bli strandad på en flygplats i tre dygn och trivas?",
  "Vem är mest trolig att bli uppgraderad till första klass av ren tur?",
  "Vem är mest trolig att prata med sin sätesgranne hela flygresan?",
  "Vem är mest trolig att somna innan planet ens lyft?",
  "Vem är mest trolig att klappa flygvärden på axeln var femte minut?",
  "Vem är mest trolig att packa bara handbagage till tre veckor?",
  "Vem är mest trolig att betala övervikt på varje resa?",
  "Vem är mest trolig att ta med strykjärn på semestern?",
  "Vem är mest trolig att glömma laddaren i varje hotellrum?",
  "Vem är mest trolig att samla hotelltvålar som troféer?",
  "Vem är mest trolig att lära sig språket innan varje resa?",
  "Vem är mest trolig att klara sig på charader i alla länder?",
  "Vem är mest trolig att beställa fel maträtt utomlands och älska den?",
  "Vem är mest trolig att få matförgiftning första dagen?",
  "Vem är mest trolig att bli solbränd genom molnen?",
  "Vem är mest trolig att ligga i skuggan hela semestern?",
  "Vem är mest trolig att planera semesterns varje minut i schema?",
  "Vem är mest trolig att åka utan plan och bara se vad som händer?",
  "Vem är mest trolig att hitta de hemliga ställena inga turister vet om?",
  "Vem är mest trolig att bara äta på kedjerestauranger utomlands?",
  "Vem är mest trolig att bli vän med hotellpersonalen och få gratis natt?",
  "Vem är mest trolig att klaga på hotellet tills de får sviten?",
  "Vem är mest trolig att bo på vandrarhem av princip trots miljonlön?",
  "Vem är mest trolig att luffa genom ett helt land med tummen?",
  "Vem är mest trolig att cykla genom Europa?",
  "Vem är mest trolig att köra bil till Italien hellre än att flyga?",
  "Vem är mest trolig att sjunga hela vägen på roadtrippen?",
  "Vem är mest trolig att somna direkt i bilen och vakna framme?",
  "Vem är mest trolig att navigera fel och upptäcka något bättre?",
  "Vem är mest trolig att vägra fråga om vägen av stolthet?",
  "Vem är mest trolig att bli kvar på en ö för att båten gick?",
  "Vem är mest trolig att hoppa i havet med kläderna på?",
  "Vem är mest trolig att prova alla vattensporter på en dag?",
  "Vem är mest trolig att bli väldigt sjösjuk på en lugn sjö?",
  "Vem är mest trolig att köpa båt efter en seglingskurs?",
  "Vem är mest trolig att bli dykcertifierad på semestern?",
  "Vem är mest trolig att paniksimma från en ofarlig fisk?",
  "Vem är mest trolig att klappa vilda djur mot alla råd?",
  "Vem är mest trolig att bli jagad av en apa som stal deras väska?",
  "Vem är mest trolig att mata måsar och ångra det direkt?",
  "Vem är mest trolig att åka på safari och somna vid lejonen?",
  "Vem är mest trolig att fota varenda solnedgång i en vecka?",
  "Vem är mest trolig att köpa souvenirer till hela släkten?",
  "Vem är mest trolig att köpa en hatt de aldrig kommer använda igen?",
  "Vem är mest trolig att pruta i en timme om småpengar på marknad?",
  "Vem är mest trolig att betala turistpris utan att blinka?",
  "Vem är mest trolig att gå på gratis stadsvandring och tipsa mest?",
  "Vem är mest trolig att läsa varje skylt på museet?",
  "Vem är mest trolig att springa igenom Louvren på tjugo minuter?",
  "Vem är mest trolig att stå längst i kön till en utsiktsplats?",
  "Vem är mest trolig att vandra en vecka i fjällen utan att duscha?",
  "Vem är mest trolig att ta med kaffebryggare på tältsemestern?",
  "Vem är mest trolig att sätta upp tältet fel och sova i bilen?",
  "Vem är mest trolig att bli biten av alla myggor i hela lägret?",
  "Vem är mest trolig att glömma myggmedlet men minnas kortleken?",
  "Vem är mest trolig att fiska hela semestern utan napp?",
  "Vem är mest trolig att hyra husbil och aldrig vilja lämna tillbaka den?",
  "Vem är mest trolig att åka tåg genom hela Europa med bara ryggsäck?",
  "Vem är mest trolig att missa tågstopp för att de fotade utsikten?",
  "Vem är mest trolig att bli intervjuad i lokal-TV utomlands?",
  "Vem är mest trolig att hamna på en främmande familjs bröllop utomlands?",
  "Vem är mest trolig att bli inbjuden på middag av lokalbefolkningen?",
  "Vem är mest trolig att skaffa vänner för livet på varje resa?",
  "Vem är mest trolig att skicka vykort som kommer fram efter hemkomsten?",
  "Vem är mest trolig att ringa hem varje dag från resan?",
  "Vem är mest trolig att glömma bort att meddela att de landat?",
  "Vem är mest trolig att förlänga resan på plats en vecka till?",
  "Vem är mest trolig att bli kvar utomlands ett helt år oplanerat?",
  "Vem är mest trolig att jobba på bar på en grekisk ö en sommar?",
  "Vem är mest trolig att klättra ett berg bara för att det fanns där?",
  "Vem är mest trolig att vända halvvägs upp för att fikat tog slut?",
  "Vem är mest trolig att gå vilse med karta i handen?",
  "Vem är mest trolig att hitta hem utan karta i främmande stad?",
  "Vem är mest trolig att testa världens läskigaste berg- och dalbana först?",
  "Vem är mest trolig att skrika högst i den snällaste karusellen?",
  "Vem är mest trolig att åka till samma ställe trettio år i rad?",
  "Vem är mest trolig att aldrig åka till samma ställe två gånger?",
  "Vem är mest trolig att semestra i Sverige och säga att det slår Medelhavet?",
  "Vem är mest trolig att boka nordligaste hotellet för norrskenets skull?",
  "Vem är mest trolig att bada i alla världshav innan 50?",
  "Vem är mest trolig att gå polarexpedition som semester?",
  "Vem är mest trolig att övertala alla till gruppresa och sedan styra allt?",
  "Vem är mest trolig att göra en resedagbok med klistermärken?",
  "Vem är mest trolig att filma hela resan och aldrig titta på materialet?",
  "Vem är mest trolig att tappa bagaget och leva en vecka på flygbolagets kit?",
  "Vem är mest trolig att packa upp direkt hemma samma kväll?",
  "Vem är mest trolig att ha väskan ouppackad i hallen en månad?",
  "Vem är mest trolig att planera nästa resa på flyget hem?",
  "Vem är mest trolig att säga 'hemma bäst' efter varje resa?",
  "Vem är mest trolig att flyga jorden runt utan att kolla priset?",
  "Vem är mest trolig att hitta billigaste biljetten genom sex mellanlandningar?",
];

const VANSKAP_OCH_GANGET = [
  "Vem är mest trolig att svara i telefon klockan fyra på natten om du behöver hjälp?",
  "Vem är mest trolig att glömma att svara i tre dagar?",
  "Vem är mest trolig att komma försent till sitt eget kalas?",
  "Vem är mest trolig att vara en timme tidig överallt?",
  "Vem är mest trolig att planera överraskningsfest åt någon i gänget?",
  "Vem är mest trolig att råka avslöja överraskningsfesten?",
  "Vem är mest trolig att minnas allas födelsedagar utantill?",
  "Vem är mest trolig att köpa födelsedagspresenten på vägen till kalaset?",
  "Vem är mest trolig att ge de mest genomtänkta presenterna?",
  "Vem är mest trolig att ge bort något de själva ville ha?",
  "Vem är mest trolig att starta gruppens gemensamma sparkonto?",
  "Vem är mest trolig att aldrig swisha tillbaka utan påminnelse?",
  "Vem är mest trolig att alltid ligga ute med pengar för alla?",
  "Vem är mest trolig att föreslå kompisresa varje år och fixa den?",
  "Vem är mest trolig att ställa in dagen innan?",
  "Vem är mest trolig att alltid vara redo på fem minuter?",
  "Vem är mest trolig att behöva tre timmar för att bli klar?",
  "Vem är mest trolig att vara gruppens ofrivilliga terapeut?",
  "Vem är mest trolig att ge livsråd de aldrig själva följer?",
  "Vem är mest trolig att veta allas hemligheter och avslöja noll?",
  "Vem är mest trolig att avslöja en hemlighet av bara farten?",
  "Vem är mest trolig att medla i gängets alla konflikter?",
  "Vem är mest trolig att starta gängets alla konflikter?",
  "Vem är mest trolig att sura längst efter ett spelkväll-bråk?",
  "Vem är mest trolig att be om ursäkt först?",
  "Vem är mest trolig att hålla en grudge i tio år över en pizzabit?",
  "Vem är mest trolig att försvara sina vänner mot vem som helst?",
  "Vem är mest trolig att skriva längsta grattis-hyllningen på födelsedagar?",
  "Vem är mest trolig att bara skriva 'grattis' utan utropstecken?",
  "Vem är mest trolig att organisera gruppens alla evenemang?",
  "Vem är mest trolig att bara dyka upp och undra vad planen är?",
  "Vem är mest trolig att ha ett reservbatteri av allt när gänget behöver?",
  "Vem är mest trolig att låna och aldrig lämna tillbaka?",
  "Vem är mest trolig att ha kvar en lånad tröja i fem år?",
  "Vem är mest trolig att flytta långt bort men höras av mest?",
  "Vem är mest trolig att bo närmast och synas minst?",
  "Vem är mest trolig att bli vän med ens föräldrar på riktigt?",
  "Vem är mest trolig att ens föräldrar frågar efter mest?",
  "Vem är mest trolig att bli kvar och prata i dörren i en timme?",
  "Vem är mest trolig att säga 'nu drar vi' och stanna två timmar till?",
  "Vem är mest trolig att somna först på filmkvällen?",
  "Vem är mest trolig att välja filmen i fyrtio minuter?",
  "Vem är mest trolig att prata genom hela filmen?",
  "Vem är mest trolig att ta med snacks till hela gänget oombedd?",
  "Vem är mest trolig att äta upp gängets snacks innan alla kommit?",
  "Vem är mest trolig att starta vattenkrig på midsommar?",
  "Vem är mest trolig att ta sällskapsspelet på blodigt allvar?",
  "Vem är mest trolig att byta regler mitt i spelet när de förlorar?",
  "Vem är mest trolig att låta någon annan vinna för stämningens skull?",
  "Vem är mest trolig att komma ihåg exakt vem som fuskade 2019?",
  "Vem är mest trolig att citera gamla interna skämt dagligen?",
  "Vem är mest trolig att skratta åt skämtet tre minuter för sent?",
  "Vem är mest trolig att skratta så att alla andra börjar skratta?",
  "Vem är mest trolig att härma alla i gänget perfekt?",
  "Vem är mest trolig att bli förolämpad av sin egen imitation?",
  "Vem är mest trolig att ordna picknick med filt och korgar och allt?",
  "Vem är mest trolig att glömma det enda de skulle ta med?",
  "Vem är mest trolig att bli gängets chaufför för alltid?",
  "Vem är mest trolig att aldrig ta körkort och alltid få skjuts?",
  "Vem är mest trolig att sitta fram och styra musiken utan att fråga?",
  "Vem är mest trolig att ha gängets bästa spellista?",
  "Vem är mest trolig att spela samma fem låtar i tio år?",
  "Vem är mest trolig att boka stugan för gängets årliga helg?",
  "Vem är mest trolig att ta bästa sängen i stugan utan diskussion?",
  "Vem är mest trolig att frivilligt sova på golvet?",
  "Vem är mest trolig att snarka så hela stugan hör?",
  "Vem är mest trolig att stiga upp först och fixa frukost åt alla?",
  "Vem är mest trolig att sova till lunch och missa frukosten?",
  "Vem är mest trolig att diska allt utan att någon bett om det?",
  "Vem är mest trolig att 'inte se' disken i tre dagar?",
  "Vem är mest trolig att vinna gängets alla vadslagningar?",
  "Vem är mest trolig att föreslå vad de omöjligt kan vinna?",
  "Vem är mest trolig att hålla koll på gängets alla planer i huvudet?",
  "Vem är mest trolig att dubbelboka sig varje helg?",
  "Vem är mest trolig att svara 'kanske' på varje inbjudan?",
  "Vem är mest trolig att tacka ja direkt utan att kolla kalendern?",
  "Vem är mest trolig att bli den som alla ringer vid flytt?",
  "Vem är mest trolig att 'ha ont i ryggen' på varje flyttdag?",
  "Vem är mest trolig att packa flyttlådor med etiketter och färgkoder?",
  "Vem är mest trolig att flytta med soppåsar som packmaterial?",
  "Vem är mest trolig att bli gudförälder till flest barn?",
  "Vem är mest trolig att bli den vuxna som barnen älskar mest?",
  "Vem är mest trolig att lära gängets barn olämpliga ord?",
  "Vem är mest trolig att starta tradition som gänget håller i 20 år?",
  "Vem är mest trolig att glömma traditionens ursprung men försvara den hårdast?",
  "Vem är mest trolig att ringa istället för att sms:a, alltid?",
  "Vem är mest trolig att skicka röstmeddelande på sju minuter?",
  "Vem är mest trolig att lyssna på röstmeddelanden en vecka senare?",
  "Vem är mest trolig att hålla tal på allas bröllop?",
  "Vem är mest trolig att bli tillfrågad som bestman eller tärna av flest?",
  "Vem är mest trolig att ordna svensexan eller möhippan som går till historien?",
  "Vem är mest trolig att gråta först under bröllopstalet?",
  "Vem är mest trolig att känna alla på stan var de än går?",
  "Vem är mest trolig att stanna och prata med alla de känner?",
  "Vem är mest trolig att låtsas inte se bekanta för att slippa småprat?",
  "Vem är mest trolig att bjuda hem hela gänget spontant en tisdag?",
  "Vem är mest trolig att ha ett hem där alla alltid är välkomna?",
  "Vem är mest trolig att vara den som gänget skulle välja som statsminister?",
  "Vem är mest trolig att vara limmet som håller ihop hela gänget?",
];

const VILDA_KORT = [
  "Vem är mest trolig att överleva ensam i skogen en månad?",
  "Vem är mest trolig att bli utomjordingarnas förstahandsval?",
  "Vem är mest trolig att förhandla fram världsfred?",
  "Vem är mest trolig att råka starta ett internationellt diplomatiskt kaos?",
  "Vem är mest trolig att vinna Nobelpriset?",
  "Vem är mest trolig att sova genom en jordbävning?",
  "Vem är mest trolig att bli väckt av sin egen snarkning?",
  "Vem är mest trolig att prata i sömnen och avslöja hemligheter?",
  "Vem är mest trolig att gå i sömnen till kylskåpet?",
  "Vem är mest trolig att drömma mardrömmar om möten?",
  "Vem är mest trolig att komma ihåg sina drömmar i detalj varje dag?",
  "Vem är mest trolig att bli hypnotiserad på en show?",
  "Vem är mest trolig att vara omöjlig att hypnotisera av ren envishet?",
  "Vem är mest trolig att tro på spöken efter en natt i gammalt hus?",
  "Vem är mest trolig att sova gott i ett spökhus?",
  "Vem är mest trolig att kolla horoskopet innan viktiga beslut?",
  "Vem är mest trolig att avfärda horoskop men läsa det i smyg?",
  "Vem är mest trolig att vinna på skraplott och köpa hundra till?",
  "Vem är mest trolig att hitta en hundralapp på gatan varje månad?",
  "Vem är mest trolig att lämna in en hittad plånbok orörd?",
  "Vem är mest trolig att bli fast i en hiss och hålla föredrag om lugn?",
  "Vem är mest trolig att få panik i hissen på tio sekunder?",
  "Vem är mest trolig att trycka på alla knappar i hissen som vuxen?",
  "Vem är mest trolig att bli inlåst på ett museum över natten?",
  "Vem är mest trolig att larma hela kvarteret med sitt eget inbrottslarm?",
  "Vem är mest trolig att glömma sin egen adress under press?",
  "Vem är mest trolig att vinna en frågesport om helt onödig kunskap?",
  "Vem är mest trolig att kunna alla huvudstäder men glömma sin portkod?",
  "Vem är mest trolig att lösa ett korsord på rekordtid?",
  "Vem är mest trolig att fylla i korsord med fel svar med självförtroende?",
  "Vem är mest trolig att bli scenmänniska på improteater?",
  "Vem är mest trolig att svimma på scen av nervositet?",
  "Vem är mest trolig att bli dragen upp på scen av en trollkarl?",
  "Vem är mest trolig att avslöja trollkarlens trick högt?",
  "Vem är mest trolig att bli statist i en film och få egen replik?",
  "Vem är mest trolig att klippas bort ur alla scener?",
  "Vem är mest trolig att skriva en insändare om vädret?",
  "Vem är mest trolig att prata om vädret i tjugo minuter, engagerat?",
  "Vem är mest trolig att bära shorts i november?",
  "Vem är mest trolig att ha vantar på sig i maj?",
  "Vem är mest trolig att bygga världens största snögubbe?",
  "Vem är mest trolig att kasta första snöbollen varje vinter?",
  "Vem är mest trolig att halka på isen och resa sig som om inget hänt?",
  "Vem är mest trolig att mata fåglar tills de blir stammisar?",
  "Vem är mest trolig att adoptera en katt som 'bara följde efter hem'?",
  "Vem är mest trolig att skaffa orm som husdjur?",
  "Vem är mest trolig att prata med sina växter?",
  "Vem är mest trolig att bygga en koja som vuxen och älska den?",
  "Vem är mest trolig att vinna en sandslottstävling?",
  "Vem är mest trolig att gräva ner sig själv i sanden frivilligt?",
  "Vem är mest trolig att starta en vattenballongkrig på stranden?",
  "Vem är mest trolig att läsa en hel bok på stranden utan att bada?",
  "Vem är mest trolig att samla snäckor som en drake samlar guld?",
  "Vem är mest trolig att bli solbränd i form av sina solglasögon?",
  "Vem är mest trolig att vinna limbotävlingen på stranden?",
  "Vem är mest trolig att utse sig själv till grillplatsens säkerhetschef?",
  "Vem är mest trolig att tappa greppet om en flygande drake direkt?",
  "Vem är mest trolig att bygga möbler utan instruktioner och lyckas?",
  "Vem är mest trolig att ha tre skruvar över efter varje bygge?",
  "Vem är mest trolig att måla om ett rum mitt i natten på impuls?",
  "Vem är mest trolig att börja fem hobbyprojekt och avsluta noll?",
  "Vem är mest trolig att bli sjukt bra på något helt onödigt?",
  "Vem är mest trolig att lära sig jonglera på en helg?",
  "Vem är mest trolig att kunna vissla på fingrarna högst?",
  "Vem är mest trolig att inte kunna vissla alls men försöka i åratal?",
  "Vem är mest trolig att vinna en stirrtävling?",
  "Vem är mest trolig att skratta först i 'skratta inte'-utmaningen?",
  "Vem är mest trolig att klara en hel dag utan att klaga?",
  "Vem är mest trolig att klaga på utmaningen 'klaga inte'?",
  "Vem är mest trolig att bli månadens kund på sitt stamställe?",
  "Vem är mest trolig att bli igenkänd av personalen på tre olika fik?",
  "Vem är mest trolig att glömma varför de gick in i ett rum, tre gånger i rad?",
  "Vem är mest trolig att hitta saker alla andra letat efter i timmar?",
  "Vem är mest trolig att packa picknick till en tio minuters promenad?",
  "Vem är mest trolig att gå ut med soporna i finkläder?",
  "Vem är mest trolig att vinna melodikrysset varje lördag?",
  "Vem är mest trolig att kunna texten till varje reklamjingel?",
  "Vem är mest trolig att sjunga i duschen så grannarna hör?",
  "Vem är mest trolig att dansa i köket medan de lagar mat?",
  "Vem är mest trolig att ha en hel koreografi till sin favoritlåt?",
  "Vem är mest trolig att starta konfettiregn på fel möte?",
  "Vem är mest trolig att beställa en överraskning till sig själv och glömma det?",
  "Vem är mest trolig att skriva dagbok i trettio år?",
  "Vem är mest trolig att hitta sin gamla dagbok och bränna den?",
  "Vem är mest trolig att spara varje biobiljett de någonsin köpt?",
  "Vem är mest trolig att slänga något viktigt i städraseri?",
  "Vem är mest trolig att städa hela huset klockan två på natten?",
  "Vem är mest trolig att ha ett 'lådan med sladdar'-museum?",
  "Vem är mest trolig att vinna på bingo första gången de spelar?",
  "Vem är mest trolig att ropa 'BINGO' på fel rad?",
  "Vem är mest trolig att bli kompis med alla pensionärer på bingon?",
  "Vem är mest trolig att lära sig ett magiskt korttrick och visa det jämt?",
  "Vem är mest trolig att avslöja sitt eget korttrick av misstag?",
  "Vem är mest trolig att vinna gruppens quizkväll ensam mot lag?",
  "Vem är mest trolig att svara snabbast och felast på quiz?",
  "Vem är mest trolig att bli utsedd till 'mest förändrad' på återträffen?",
  "Vem är mest trolig att vara exakt likadan som i skolan?",
  "Vem är mest trolig att göra allt det här till en historia värd att berätta?",
  "Vem är mest trolig att vara den som alla kommer sakna mest på festen de missar?",
  "Vem är mest trolig att läsa alla dessa frågor högt bäst?",
];

/** Hela poolen — 1096 frågor. */
export const MOST_LIKELY_TO: string[] = [
  ...FEST_OCH_FYLLA,
  ...KARLEK_OCH_DEJTING,
  ...PENGAR_OCH_KARRIAR,
  ...PINSAMT_OCH_VARDAG,
  ...FRAMTID_OCH_LIVET,
  ...SPORT_OCH_HALSA,
  ...MAT_OCH_DRYCK,
  ...TEKNIK_OCH_SOME,
  ...RESOR_OCH_AVENTYR,
  ...VANSKAP_OCH_GANGET,
  ...VILDA_KORT,
];
